### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-protocol#11]
Pre issue dependencies (pip freeze):
```
appdirs==1.4.3
asgi-redis==1.3.0
asgiref==1.1.2
attrs==17.3.0
autobahn==17.10.1
Automat==0.6.0
bleach==1.5.0
channels==1.1.8
constantly==15.1.0
coverage==4.4.1
daphne==1.3.0
defusedxml==0.5.0
Django==1.10.8
django-redis==4.7.0
django-redis-sessions==0.5.6
djangorestframework==3.4.7
fakeredis==0.8.2
flake8==3.4.1
html5lib==0.9999999
hyperlink==17.3.1
incremental==17.5.0
isodate==0.6.0
isort==4.2.5
jsonfield==1.0.3
lxml==4.1.1
mccabe==0.6.1
msgpack-python==0.4.8
mypy==0.530
mypy-extensions==0.3.0
openslides==2.1.1
packaging==16.8
pkg-resources==0.0.0
pkgconfig==1.2.2
psycopg2==2.7.3.2
pycodestyle==2.3.1
pyflakes==1.5.0
pyparsing==2.2.0
PyPDF2==1.26.0
python3-saml==1.3.0
redis==2.10.6
roman==2.0.0
six==1.11.0
Twisted==17.9.0
txaio==2.8.2
txredisapi==1.4.4
typed-ast==1.1.0
xmlsec==1.3.3
zope.interface==4.4.3
```

Then `pip install -U -r requirements.txt`:
```
[...]
Installing collected packages: pyflakes, flake8, async-timeout, asgiref, daphne, channels, attrs
  Found existing installation: pyflakes 1.5.0
    Uninstalling pyflakes-1.5.0:
      Successfully uninstalled pyflakes-1.5.0
  Found existing installation: flake8 3.4.1
    Uninstalling flake8-3.4.1:
      Successfully uninstalled flake8-3.4.1
  Found existing installation: asgiref 1.1.2
    Uninstalling asgiref-1.1.2:
      Successfully uninstalled asgiref-1.1.2
  Found existing installation: daphne 1.3.0
    Uninstalling daphne-1.3.0:
      Successfully uninstalled daphne-1.3.0
  Found existing installation: channels 1.1.8
    Uninstalling channels-1.1.8:
      Successfully uninstalled channels-1.1.8
  Found existing installation: attrs 17.3.0
    Uninstalling attrs-17.3.0:
      Successfully uninstalled attrs-17.3.0
Successfully installed asgiref-2.1.4 async-timeout-2.0.0 attrs-17.4.0 channels-1.0.3 daphne-2.0.3 flake8-3.5.0 pyflakes-1.6.0
```

After this a `pip freeze` again:
```
appdirs==1.4.3
asgi-redis==1.3.0
asgiref==2.1.4
async-timeout==2.0.0
attrs==17.4.0
autobahn==17.10.1
Automat==0.6.0
bleach==1.5.0
channels==1.0.3
constantly==15.1.0
coverage==4.4.1
daphne==2.0.3
defusedxml==0.5.0
Django==1.10.8
django-redis==4.7.0
django-redis-sessions==0.5.6
djangorestframework==3.4.7
fakeredis==0.8.2
flake8==3.5.0
html5lib==0.9999999
hyperlink==17.3.1
incremental==17.5.0
isodate==0.6.0
isort==4.2.5
jsonfield==1.0.3
lxml==4.1.1
mccabe==0.6.1
msgpack-python==0.4.8
mypy==0.530
mypy-extensions==0.3.0
openslides==2.1.1
packaging==16.8
pkg-resources==0.0.0
pkgconfig==1.2.2
psycopg2==2.7.3.2
pycodestyle==2.3.1
pyflakes==1.6.0
pyparsing==2.2.0
PyPDF2==1.26.0
python3-saml==1.3.0
redis==2.10.6
roman==2.0.0
six==1.11.0
Twisted==17.9.0
txaio==2.8.2
txredisapi==1.4.4
typed-ast==1.1.0
xmlsec==1.3.3
zope.interface==4.4.3
```

The test (`PYTHONPATH=./ DJANGO_SETTINGS_MODULE='tests.settings' openslides test`) crashes with:
```
Traceback (most recent call last):
  File "/home/finn/OpenSlides/.venv/bin/openslides", line 11, in <module>
    sys.exit(main())
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/openslides/__main__.py", line 40, in main
    execute_from_command_line(sys.argv)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/apps.py", line 22, in ready
    monkeypatch_django()
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/hacks.py", line 10, in monkeypatch_django
    from .management.commands.runserver import Command as RunserverCommand
  File "/home/finn/OpenSlides/.venv/lib/python3.5/site-packages/channels/management/commands/runserver.py", line 5, in <module>
    from daphne.server import Server, build_endpoint_description_strings
ImportError: cannot import name 'build_endpoint_description_strings'
```

Note: I use a shared venv for openslides and all plugins; so there are packages without interest here. I need to check for updated (broken) dependencies.

**Comment by FinnStutzenstein** [comment]
Ok, daphne 2.x was released and pip upgrades daphne, becuase OpenSlides does not directly require daphne. Because OpenSlides uses channels, daphne is installed, but OS lockes channels to a lower version which requires daphne 1.x. Locked daphne explicitly in #8 .
